- Print "top-level" instead of "class '::'" in   NoSuchMethodErrors.
Review URL: https://codereview.chromium.org//13982018

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@22005 260f80e4-7a28-3924-810f-c04153c831b5