Invoke noSuchMethod instead of immediately throwing NoSuchMethodError when invoking a non-closure as a closure (reopened issue 3326). Address comments of last cl. Review URL: https://codereview.chromium.org//11612002
git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@16220 260f80e4-7a28-3924-810f-c04153c831b5