Disable profiler, as profiler shutdown is racing with isolates.
Some tests using isolates, crashes with the following assertion error:

  runtime/vm/profiler.cc:237: error: expected: initialized_

It turns out that ProfileManager::Shutdown is called, while there are still isolates running. The comment in runtime/vm/dart.cc:152 seams to explain the issue.

BUG=
R=sgjesse@google.com

Review URL: https://codereview.chromium.org//87643003

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@30666 260f80e4-7a28-3924-810f-c04153c831b5