Fix another unused-private-field clang error.
../../runtime/vm/intermediate_language.h:1093:20: error: private field 'block_entry_' is not used [-Werror,-Wunused-private-field]
  BlockEntryInstr* block_entry_;

R=kmillikin@google.com

Signed-off-by: Thiago Farina <tfarina@chromium.org>

Review URL: https://codereview.chromium.org//14341012

Patch from Thiago Farina <tfarina@chromium.org>.

git-svn-id: https://dart.googlecode.com/svn/branches/bleeding_edge@21876 260f80e4-7a28-3924-810f-c04153c831b5